volumes:
  puma-sock:

services:
  db:
    image: postgres:15
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - type: bind
        source: ${APP_CODE_PATH_HOST}/public
        target: /var/www/public
        consistency: cached
      - type: volume
        source: puma-sock
        target: /var/www/tmp/sockets
        volume:
          nocopy: true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec puma -e development
    ports:
      - ${APP_PORT}:3000
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: $APP_CODE_PATH_HOST
        target: /var/www
        consistency: cached
      - type: volume
        source: puma-sock
        target: /var/www/tmp/sockets
        volume:
          nocopy: true
    depends_on:
      - db
